permission: 'timsixth.voucher'
messages:
  no_permission: '&cYou dont have premission'
  correct_use: '&cCorrect use: /voucher list|give|gui|reload <name> <player>'
  added_voucher: '&aVoucher has added to your inventory'
  doesnt_exists: '&cThis voucher doesnt exists!'
  offline_player: '&cThis player is offline'
  added_voucher_other_player: '&aYou have added voucher to player {PLAYER_NAME}'
  created_voucher: '&aSuccessfully created voucher'
  updated_voucher: '&aVoucher has been updated successfully'
  deleted_voucher: '&aSuccessfully deleted voucher'
  type_voucher_name: '&eType voucher''s name (Name is id of your voucher)'
  type_voucher_display_name: '&eType voucher''s display name (You can use colored messages).'
  type_voucher_command: '&eType voucher''s command'
  type_voucher_lore: '&eType voucher''s lore. Type "|" if do you want new line in lore. (You can use colored messages)'
  set_voucher_enchants: '&eSet voucher''s enchants'
  cancel_process: '&cIf do you want cancel this process,you will type "cancel" in chat.'
  voucher_already_exits: '&cThis voucher already exists'
  invalid_name_format: '&cIn voucher''s name you can only use letters and numbers'
  clear_all_today_logs: '&aSuccessfully cleared logs which created today'
  files_reloaded: '&aFiles have been reloaded successfully'