permission: 'timsixth.voucher'
items_per_page: 40
gui_size: 54
vouchers_gui_name: "&aVouchers"
logs_gui_name: "&aLogs"
use_confirmation_menu: false #If this option is true, when you want to use voucher you have to confirm redeem
inputs_names:
  name: "&aType voucher name"
  display_name: "&aType voucher display name"
  material: "&aType voucher material"
discord:
  webhook:
    url: ''
    name: 'T-Vouchers' #you can use {PLUGIN_VERSION} in this field
    avatar_url: 'https://www.spigotmc.org/data/resource_icons/93/93682.jpg?1642107439'
  message:
    content: 'Voucher {VOUCHER_DISPLAY_NAME_WITH_STRIPED_COLORS} has been redeemed by {PLAYER_NAME}'
  embed:
    description: 'Voucher {VOUCHER_DISPLAY_NAME_WITH_STRIPED_COLORS} has been redeemed by {PLAYER_NAME}'
    title: 'Voucher v{PLUGIN_VERSION}'
    author:
      name: 'Vouchers v{PLUGIN_VERSION}'
      icon_url: 'https://www.spigotmc.org/data/resource_icons/93/93682.jpg?1642107439'
    footer:
      icon_url: 'https://www.spigotmc.org/data/resource_icons/93/93682.jpg?1642107439'
    timestamp: '2025-05-21T22:00:00.000Z'
    image_url: 'https://www.spigotmc.org/data/resource_icons/93/93682.jpg?1642107439'
    thumbnail_url: 'https://www.spigotmc.org/data/resource_icons/93/93682.jpg?1642107439'
    color: '#32b834' #only in HEX
messages:
  no_permission: '&cYou dont have premission'
  only_players_can_use_this_command: 'Only players can use this command'
  added_voucher: '&aVoucher has added to your inventory'
  doesnt_exists: '&cThis voucher doesn''t exists!'
  offline_player: '&cThis player is offline'
  added_voucher_other_player: '&aYou have added voucher to player {PLAYER_NAME}'
  created_voucher: '&aSuccessfully created voucher'
  updated_voucher: '&aVoucher has been updated successfully'
  deleted_voucher: '&aSuccessfully deleted voucher'
  type_voucher_name: '&eType voucher''s name (Name is id of your voucher)'
  type_voucher_display_name: '&eType voucher''s display name (You can use colored messages).'
  type_voucher_command: '&eType voucher''s command. You can use {NICK} as user nickname, Type "|" if do you want more than one command'
  type_voucher_lore: '&eType voucher''s lore. Type "|" if do you want new line in lore. (You can use colored messages)'
  type_voucher_material: '&eType voucher material, default material is paper. Materials must be written uppercase. Type "none" to continue with default material'
  set_voucher_enchants: '&eSet voucher''s enchants'
  cancel_process: '&cIf do you want cancel this process,you will type "cancel" in chat.'
  voucher_already_exits: '&cThis voucher already exists'
  invalid_name_format: '&cIn voucher''s name you can only use letters and numbers'
  clear_all_today_logs: '&aSuccessfully cleared logs which created today'
  files_reloaded: '&aFiles have been reloaded successfully'
  added_voucher_to_everyone: '&aYou have given voucher everyone'
  used_voucher: '&aYou have redeemed {VOUCHER_DISPLAY_NAME} &avoucher'
  not_number: '&cThis is not a number'
  voucher_redeem_rejected: '&cYou have rejected voucher redeem'
  service_unavailable: '&cThe version checker service is unavailable'
  please_update_plugin: '&c[{PLUGIN_NAME}] Please update plugin to newest version.'
  plugin_version_on_the_server: '&ePlugin version on your server: {PLUGIN_VERSION}'
  current_plugin_version: '&eCurrent plugin version: {PLUGIN_CURRENT_VERSION}'
  plugin_up_to_date: '&a[{PLUGIN_NAME}] is up to date'
  commands_list:
    - '&7---------] &aVouchers &7[---------'
    - '&7/&avoucher reload &8- &7Reloads configuration files'
    - '&7/&avoucher list &8- &7List of all vouchers'
    - '&7/&avoucher gui &8- &7Opens gui manager for vouchers'
    - '&7/&avoucher give <voucher> <player|amount> <amount> &8- &7Gives voucher'
    - '&7/&avoucher giveall <voucher> <amount> &8- &7Gives voucher for everyone'