permission: 'timsixth.voucher'
items_per_page: 40
gui_size: 54
vouchers_gui_name: "&aVouchers"
logs_gui_name: "&aLogs"
use_confirmation_menu: false #If this option is true, when you want to use voucher you have to confirm redeem
inputs_names:
  name: "&aType voucher name"
  display_name: "&aType voucher display name"
  material: "&aType voucher material"
messages:
  no_permission: '&cYou dont have premission'
  added_voucher: '&aVoucher has added to your inventory'
  doesnt_exists: '&cThis voucher doesn''t exists!'
  offline_player: '&cThis player is offline'
  added_voucher_other_player: '&aYou have added voucher to player {PLAYER_NAME}'
  created_voucher: '&aSuccessfully created voucher'
  updated_voucher: '&aVoucher has been updated successfully'
  deleted_voucher: '&aSuccessfully deleted voucher'
  type_voucher_name: '&eType voucher''s name (Name is id of your voucher)'
  type_voucher_display_name: '&eType voucher''s display name (You can use colored messages).'
  type_voucher_command: '&eType voucher''s command. You can use {NICK} as user nickname, Type "|" if do you want more than one command'
  type_voucher_lore: '&eType voucher''s lore. Type "|" if do you want new line in lore. (You can use colored messages)'
  type_voucher_material: '&eType voucher material, default material is paper. Materials must be written uppercase. Type "none" to continue with default material'
  set_voucher_enchants: '&eSet voucher''s enchants'
  cancel_process: '&cIf do you want cancel this process,you will type "cancel" in chat.'
  voucher_already_exits: '&cThis voucher already exists'
  invalid_name_format: '&cIn voucher''s name you can only use letters and numbers'
  clear_all_today_logs: '&aSuccessfully cleared logs which created today'
  files_reloaded: '&aFiles have been reloaded successfully'
  added_voucher_to_everyone: '&aYou have given voucher everyone'
  used_voucher: '&aYou have redeemed {VOUCHER_DISPLAY_NAME} &avoucher'
  not_number: '&cThis is not a number'
  voucher_redeem_rejected: '&cYou have rejected voucher redeem'
  commands_list:
    - '&7---------] &aVouchers &7[---------'
    - '&7/&avoucher reload &8- &7Reloads configuration files'
    - '&7/&avoucher list &8- &7List of all vouchers'
    - '&7/&avoucher gui &8- &7Opens gui manager for vouchers'
    - '&7/&avoucher give <voucher> <player|amount> <amount> &8- &7Gives voucher'
    - '&7/&avoucher giveall <voucher> <amount> &8- &7Gives voucher for everyone'